// <auto-generated />
namespace GreenEye.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updateDebit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDebit));
        
        string IMigrationMetadata.Id
        {
            get { return "202204161623212_updateDebit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
