// <auto-generated />
namespace GreenEye.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ConnectBook_Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConnectBook_Order));
        
        string IMigrationMetadata.Id
        {
            get { return "202204161721101_ConnectBook_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
